import { useState } from "react";
import { Award, ExternalLink, RefreshCw, ShieldCheck, ShieldX } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";

export function CertificateGovernancePanel({ projectId, blindTag, permissions }: { projectId: string; blindTag: string; permissions: any }) {
  const readiness = trpc.certificates.readiness.useQuery({ projectId, blindTag });
  const list = trpc.certificates.list.useQuery({ projectId, blindTag });
  const [mode, setMode] = useState<"issue" | "reissue" | "revoke" | null>(null);
  const [reason, setReason] = useState("");
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const refresh = async () => { await readiness.refetch(); await list.refetch(); };
  const issue = trpc.certificates.issue.useMutation({ onSuccess: async (result) => { toast.success(`${result.certificateNumber} issued and locked.`); setMode(null); setReason(""); await refresh(); }, onError: (error) => toast.error(error.message) });
  const revoke = trpc.certificates.revoke.useMutation({ onSuccess: async () => { toast.success("Certificate revoked with permanent reason."); setMode(null); setReason(""); await refresh(); }, onError: (error) => toast.error(error.message) });
  const current = list.data?.find((row: any) => row.status === "issued");
  return <Card className="overflow-hidden border-border"><CardHeader className="border-b border-border/70 bg-muted/20"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle className="flex items-center gap-2 text-base"><Award className="h-4 w-4 text-emerald-700" /> Certificate Governance</CardTitle><CardDescription>Issue an immutable, versioned and SHA-256-hashed certificate snapshot only after all gates pass.</CardDescription></div><Badge variant="outline" className={readiness.data?.ready ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-amber-200 bg-amber-50 text-amber-800"}>{readiness.data?.ready ? "Ready to issue" : "Blocked"}</Badge></div></CardHeader><CardContent className="space-y-4 p-4">
    {!readiness.data?.ready && <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">{readiness.data?.blockingReasons.map((reason: string) => <p key={reason}>• {reason}</p>)}</div>}
    <div className="flex flex-wrap gap-2">{!current && permissions.canIssueCertificate && <Button disabled={!readiness.data?.ready} className="gap-2" onClick={() => setMode("issue")}><ShieldCheck className="h-4 w-4" /> Issue Final Certificate</Button>}{current && permissions.canReissueCertificate && <Button variant="outline" className="gap-2" onClick={() => setMode("reissue")}><RefreshCw className="h-4 w-4" /> Controlled Reissue</Button>}{current && permissions.canRevokeCertificate && <Button variant="outline" className="gap-2 border-red-200 text-red-700" onClick={() => { setSelectedId(current.id); setMode("revoke"); }}><ShieldX className="h-4 w-4" /> Revoke</Button>}</div>
    {(list.data ?? []).length ? <div className="space-y-2">{list.data?.map((cert: any) => <div key={cert.id} className="flex flex-col gap-3 rounded-xl border border-border p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-foreground">{cert.certificateNumber}</p><p className="mt-1 text-xs text-muted-foreground">Version {cert.version} · Hash {cert.snapshotHash.slice(0, 16)}… · {new Date(cert.issuedAt).toLocaleString()}</p></div><div className="flex items-center gap-2"><Badge variant="outline">{cert.status}</Badge><a className="inline-flex items-center gap-1 text-xs font-bold text-primary" href={`/certificate/verify/${cert.verificationToken}`} target="_blank" rel="noreferrer">Open locked copy <ExternalLink className="h-3.5 w-3.5" /></a></div></div>)}</div> : <div className="rounded-xl border border-dashed border-border p-4 text-center text-xs text-muted-foreground">No governed certificate has been issued.</div>}
  </CardContent><Dialog open={Boolean(mode)} onOpenChange={(value) => !value && setMode(null)}><DialogContent><DialogHeader><DialogTitle>{mode === "issue" ? "Issue Final Certificate" : mode === "reissue" ? "Controlled Certificate Reissue" : "Revoke Certificate"}</DialogTitle><DialogDescription>{mode === "issue" ? "The source records are frozen into an immutable snapshot and hashed." : "A reason is permanently stored in the certificate history."}</DialogDescription></DialogHeader><Textarea rows={4} value={reason} onChange={(event) => setReason(event.target.value)} placeholder={mode === "issue" ? "Optional initial issue note" : "Required reason"} /><DialogFooter><Button variant="outline" onClick={() => setMode(null)}>Cancel</Button><Button disabled={(mode !== "issue" && reason.trim().length < 5) || issue.isPending || revoke.isPending} onClick={() => mode === "revoke" ? revoke.mutate({ certificateId: selectedId!, reason }) : issue.mutate({ projectId, blindTag, reason: reason || null, reissue: mode === "reissue" })}>{issue.isPending || revoke.isPending ? "Saving..." : "Confirm"}</Button></DialogFooter></DialogContent></Dialog></Card>;
}
